<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'basket' => '/../db/migrations/20190212025922_basket.php',
                'basketseeder' => '/../db/seeds/BasketSeeder.php',
                'controller\\userscontroller' => '/Users/UsersController.php',
                'fkrelationbetweencartproductsandusers' => '/../db/migrations/20190212030537_fk_relation_between_cart_products_and_users.php',
                'interfaces\\modelinterface' => '/Interfaces/ModelInterface.php',
                'interfaces\\repositoryinterface' => '/Interfaces/RepositoryInterface.php',
                'model\\basket' => '/Users/Basket.php',
                'model\\product' => '/Users/Product.php',
                'model\\user' => '/Users/User.php',
                'product' => '/../db/migrations/20190212025341_product.php',
                'productseeder' => '/../db/seeds/ProductSeeder.php',
                'routerresolver' => '/../http/RouterResolver.php',
                'user' => '/../db/migrations/20190212023617_user.php',
                'userscontrollertest' => '/../tests/Users/UsersControllerTest.php',
                'userseeder' => '/../db/seeds/UserSeeder.php',
                'usersrepository' => '/Users/UsersRepository.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
